name: Update Bitcoin Reports

on:
  schedule:
    - cron:  '00 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Set up Python 3.10.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.13'

    - name: Verify Python Version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --force-reinstall -r requirements.txt

    - name: Print Installed Packages (Debug)
      run: pip freeze

    - name: Run the script and update the charts
      run: |
        python main.py
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin main # Pull the latest changes from the repository
        git add .
        git commit -m "Update Charts" || echo "No changes to commit"
        git push origin HEAD:main
